In [5]:
#NUMPY
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr)
print("Type: ", type(arr))
print("\nDimension: ", arr.ndim)
print("Size:  ",arr.size)
print("Shape: ",arr.shape)
print("Dtype: ",arr.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
Type:  <class 'numpy.ndarray'>

Dimension:  1
Size:   10
Shape:  (10,)
Dtype:  int64


In [ ]:
#Creating 2 dimension array
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2)
#print("Type: ", type(arr2))
print("\nDimension: ", arr2.ndim)
print("Size:  ", arr2.size)
print("Shape: ", arr2.shape)
print("Dtype: ", arr2.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Type:  <class 'numpy.ndarray'>
Dimension:  2
Size:   9
Shape:  (3, 3)
Dtype:  int64


In [ ]:
#Creating 2 dimension array
arr3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[11, 22, 33], [44,55,66], [77, 88, 99]], [[111, 222, 333], [444, 555, 666], [777, 888, 999]]])
print(arr3)
#print("Type: ", type(arr3))
print("\nDimension: ", arr3.ndim)
print("Size:  ", arr3.size)
print("Shape: ", arr3.shape)
print("Dtype: ", arr3.dtype)

[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[ 11  22  33]
  [ 44  55  66]
  [ 77  88  99]]

 [[111 222 333]
  [444 555 666]
  [777 888 999]]]

Dimension:  3
Size:   27
Shape:  (3, 3, 3)
Dtype:  int64


In [7]:
#Creating an array with dimension
arr4 = np.array([1, 2, 3, 4, 5], ndim=4)
print(arr4)
print("Dimension:",arr4.ndim)
print("Size:", arr4.size)
print("Shape:",arr4.shape)

TypeError: array() got an unexpected keyword argument 'ndim'